// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeletorFamilias.WepApp.DAO;

namespace SeletorFamilias.WepApp.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211111031223_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeletorFamilias.WepApp.Models.ConjugeFamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Renda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Conjuges");
                });

            modelBuilder.Entity("SeletorFamilias.WepApp.Models.DependenteFamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Dependentes");
                });

            modelBuilder.Entity("SeletorFamilias.WepApp.Models.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConjugeId")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConjugeId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("SeletorFamilias.WepApp.Models.ResponsavelFamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Renda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("SeletorFamilias.WepApp.Models.DependenteFamiliar", b =>
                {
                    b.HasOne("SeletorFamilias.WepApp.Models.Familia", null)
                        .WithMany("Dependentes")
                        .HasForeignKey("FamiliaId");
                });

            modelBuilder.Entity("SeletorFamilias.WepApp.Models.Familia", b =>
                {
                    b.HasOne("SeletorFamilias.WepApp.Models.ConjugeFamiliar", "Conjuge")
                        .WithMany()
                        .HasForeignKey("ConjugeId");

                    b.HasOne("SeletorFamilias.WepApp.Models.ResponsavelFamiliar", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");

                    b.Navigation("Conjuge");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SeletorFamilias.WepApp.Models.Familia", b =>
                {
                    b.Navigation("Dependentes");
                });
#pragma warning restore 612, 618
        }
    }
}
